---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=fab8-spring-boot-docker&var-version=0.1.0"
  labels:
    provider: "fabric8"
    project: "fab8-spring-boot-docker"
    version: "0.1.0"
    group: "org.springframework"
  name: "fab8-spring-boot-docker"
spec:
  replicas: 1
  selector:
    project: "fab8-spring-boot-docker"
    provider: "fabric8"
    group: "org.springframework"
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: "Rolling"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/spring-boot.svg"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=fab8-spring-boot-docker&var-version=0.1.0"
      labels:
        provider: "fabric8"
        project: "fab8-spring-boot-docker"
        version: "0.1.0"
        group: "org.springframework"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fab8/demo"
        imagePullPolicy: "IfNotPresent"
        name: "fab8-fab8-spring-boot-docker"
        securityContext:
          privileged: false
  triggers:
  - type: "ConfigChange"
