---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
  labels:
    provider: "fabric8"
    project: "fab8-spring-boot-docker"
    version: "0.1.0"
    group: "org.springframework"
  name: "fab8-spring-boot-docker"
spec:
  ports:
  - port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "fab8-spring-boot-docker"
    provider: "fabric8"
    group: "org.springframework"
  type: "LoadBalancer"
